"""add_tbl_Category

Revision ID: 2f1f65f54f5b
Revises: c63e238a5ce0
Create Date: 2026-03-16 14:40:26.021551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1f65f54f5b'
down_revision: Union[str, None] = 'c63e238a5ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Category', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('Category', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('Category', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.add_column('Category', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('Category', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('Category', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('Category', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('Product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('Product', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('Product', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('Product', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.add_column('Product', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('Product', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('Product', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('Product', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('User', sa.Column('first_name', sa.Text(), nullable=True))
    op.add_column('User', sa.Column('last_name', sa.Text(), nullable=True))
    op.add_column('User', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('User', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('User', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_deleted')
    op.drop_column('User', 'deleted_at')
    op.drop_column('User', 'deleted_by')
    op.drop_column('User', 'modified_at')
    op.drop_column('User', 'modified_by')
    op.drop_column('User', 'created_at')
    op.drop_column('User', 'created_by')
    op.drop_column('User', 'last_name')
    op.drop_column('User', 'first_name')
    op.drop_column('Product', 'is_deleted')
    op.drop_column('Product', 'deleted_at')
    op.drop_column('Product', 'deleted_by')
    op.drop_column('Product', 'modified_at')
    op.drop_column('Product', 'modified_by')
    op.drop_column('Product', 'created_at')
    op.drop_column('Product', 'created_by')
    op.drop_column('Product', 'category_id')
    op.drop_column('Category', 'is_deleted')
    op.drop_column('Category', 'deleted_at')
    op.drop_column('Category', 'deleted_by')
    op.drop_column('Category', 'modified_at')
    op.drop_column('Category', 'modified_by')
    op.drop_column('Category', 'created_at')
    op.drop_column('Category', 'created_by')
    # ### end Alembic commands ###
