"""init_db

Revision ID: c63e238a5ce0
Revises: 
Create Date: 2026-03-13 16:43:40.233981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c63e238a5ce0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Products_id'), table_name='Products')
    op.drop_table('Products')
    op.add_column('User', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'status')
    op.create_table('Products',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index(op.f('ix_Products_id'), 'Products', ['id'], unique=False)
    # ### end Alembic commands ###
