"""add refresh_token_table

Revision ID: e411831ad147
Revises: 2f1f65f54f5b
Create Date: 2026-03-20 15:43:49.301171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e411831ad147'
down_revision: Union[str, None] = '2f1f65f54f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Order_id'), table_name='Order')
    op.drop_table('Order')
    op.drop_index(op.f('ix_Cart_id'), table_name='Cart')
    op.drop_table('Cart')
    op.drop_index(op.f('ix_OrderItem_id'), table_name='OrderItem')
    op.drop_table('OrderItem')
    op.drop_index(op.f('ix_Orderitem_id'), table_name='Orderitem')
    op.drop_table('Orderitem')
    op.alter_column('RefreshToken', 'jti',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_RefreshToken_jti'), 'RefreshToken', ['jti'], unique=False)
    op.drop_constraint(op.f('UserRole_ibfk_2'), 'UserRole', type_='foreignkey')
    op.drop_constraint(op.f('UserRole_ibfk_1'), 'UserRole', type_='foreignkey')
    op.create_foreign_key(None, 'UserRole', 'Role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'UserRole', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserRole', type_='foreignkey')
    op.drop_constraint(None, 'UserRole', type_='foreignkey')
    op.create_foreign_key(op.f('UserRole_ibfk_1'), 'UserRole', 'Role', ['user_id'], ['id'])
    op.create_foreign_key(op.f('UserRole_ibfk_2'), 'UserRole', 'User', ['role_id'], ['id'])
    op.drop_index(op.f('ix_RefreshToken_jti'), table_name='RefreshToken')
    op.alter_column('RefreshToken', 'jti',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.create_table('Orderitem',
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('modified_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index(op.f('ix_Orderitem_id'), 'Orderitem', ['id'], unique=False)
    op.create_table('OrderItem',
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('modified_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index(op.f('ix_OrderItem_id'), 'OrderItem', ['id'], unique=False)
    op.create_table('Cart',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('modified_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index(op.f('ix_Cart_id'), 'Cart', ['id'], unique=False)
    op.create_table('Order',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('note', mysql.TEXT(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('modified_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('modified_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_general_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_index(op.f('ix_Order_id'), 'Order', ['id'], unique=False)
    # ### end Alembic commands ###
